### ISSUE TITLE
所有PDF均无法打开

### ISSUE THREAD

**Issue by daya-prac** [niuxinghua/SpringBooks#4]
clone后打开任意PDF文件都提示“文件已损坏”，希望能尽快查明原因并修复，非常感谢

**Comment by niuxinghua** [comment]
> clone后打开任意PDF文件都提示“文件已损坏”，希望能尽快查明原因并修复，非常感谢

链接:https://pan.baidu.com/s/1QL6s4HI1JX0rSKZHYRJQDg  密码:ajpu  github大文件损坏了 试试百度云吧

**Comment by niuxinghua** [comment]
链接:https://pan.baidu.com/s/1i00P3QNjApCnqZL5B9U2gA  密码:womr
